spring.application.name=TaxiRado
spring.datasource.url=jdbc:postgresql://postgres:5432/taxirado
spring.datasource.username=taxirado
spring.datasource.password=taxirado123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8080
